homework48/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path

from webapp.views import IndexView, ProductView, ProductCreateView, ProductUpdateView, ProductDeleteView, CartAddView, \
    CartView, CartDeleteView, CartDeleteOneView
from webapp.views.order import OrderListView, OrderDetailView, OrderCreateView, OrderUpdateView, OrderDeleteView

app_name = "webapp"


class OrderProductCreateView:
    pass


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/add-to-cart/', CartAddView.as_view(), name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/<int:pk>/delete/', CartDeleteView.as_view(), name='remove_for_cart'),
    path('cart/<int:pk>/one-delete/', CartDeleteOneView.as_view(), name='remove_one_for_cart'),
    # path('order/create/', OrderCreate.as_view(), name='order_create')
    path('order/', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>', OrderDetailView.as_view(), name='order_view'),
    path('order/create_order/', OrderCreateView.as_view(), name='order_create'),
    path('order/update_order/<int:pk>/', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
]

webapp/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator

DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = [('DEFAULT_CATEGORY', 'разное'), ('bakery', 'выпечка'), ('sweets', 'сладости'),
                    ('drinks', 'напитки'), ('veggies', 'овощи')]


class Product(models.Model):
    category = models.CharField(max_length=20, default=DEFAULT_CATEGORY, choices=CATEGORY_CHOICES,
                                verbose_name='Категория')
    p_name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    balance = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(verbose_name='Цена', max_digits=7, decimal_places=2,
                                validators=(MinValueValidator(0),))

    def str(self):
        return f"{self.p_name} - {self.balance}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        permissions = [
            ('product_create', 'Добавление товара'),
            ('product_update', 'Редактирование товара'),
            ('product_delete', 'Удаление товара'),
        ]



class Cart(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE,
                                verbose_name='Товар', related_name='in_cart')
    qty = models.PositiveIntegerField(verbose_name='Количество', default=1)

    def __str__(self):
        return f'{self.product.p_name} - {self.qty}'

    class Meta:
        verbose_name = 'Товар в корзине'
        verbose_name_plural = 'Товары в корзине'

    def get_product_total(self):
        return self.qty * self.product.price

    @classmethod
    def get_total(cls):
        total = 0
        for card in cls.objects.all():
            total += card.get_product_total()
        return total


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Пользователь', related_name='orders')
    name = models.CharField(max_length=50, verbose_name='Имя')
    phone = models.CharField(max_length=30, verbose_name='Телефон')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    products = models.ManyToManyField('webapp.Product', related_name='orders', verbose_name='Товары',
                                      through='webapp.OrderProduct', through_fields=['order', 'product'])

    def __str__(self):
        return f'{self.name} - {self.phone}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        permissions = [
            ('order_list', 'Просмотр заказов'),
            ('order_add', 'Добавить заказ')
        ]


class OrderProduct(models.Model):
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE,
                                verbose_name='Товар', related_name='order_products')
    order = models.ForeignKey('webapp.Order', on_delete=models.CASCADE,
                              verbose_name='Заказ', related_name='order_products')
    qty = models.PositiveIntegerField(verbose_name='Количество')

    def __str__(self):
        return f'{self.product.p_name} - {self.order.name}'

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from webapp.models import Product, Cart, Order


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label='Найти')


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = []


class CartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ["qty"]


# class OrderForm(forms.ModelForm):
#     class Meta:
#         model = Order
#         fields = ["name", "phone", "address"]
#

class OrderForm(ModelForm):
    def __init__(self, user=None, **kwargs):
        self.user = user
        if user and not user.is_authenticated:
            self.user = None
        super().__init__(**kwargs)

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if not self.user and not self.cleaned_data.get('name'):
            raise ValidationError('Необходимо указать логин либо его имя')
        return name

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not self.user and not self.cleaned_data.get('email'):
            raise ValidationError('Необходимо авторизоваться или указать ваш email')
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if not self.user and not self.cleaned_data.get('phone'):
            raise ValidationError('Необходимо авторизоваться или указать Ваш номер телефона')
        return phone

    class Meta:
        model = Order
        fields = ['user', 'name', 'phone']

webapp/views/base_view.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import ListView

from webapp.forms import SearchForm


class SearchView(ListView):
    search_form_class = SearchForm
    search_form_field = "search"
    query_name = "query"
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        if self.search_value:
            return self.model.objects.filter(self.get_query())
        return self.model.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["form"] = self.form
        if self.search_value:
            query = urlencode({self.search_form_field: self.search_value})
            context[self.query_name] = query
            context[self.search_form_field] = self.search_value
        return context

    def get_search_form(self):
        return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data.get(self.search_form_field)

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

webapp/views/cart.py
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView

from webapp.forms import CartForm, OrderForm
from webapp.models import Cart, Product, Order, OrderProduct


class CartAddView(CreateView):
    model = Cart
    form_class = CartForm

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        qty = form.cleaned_data.get("qty")
        if qty > product.balance:
            return HttpResponseBadRequest(
                f"Такое количество товара {product.p_name} всего {product.balance}. Добавить {qty} штук не представляется возможным")
        else:
            cart_product, is_created = Cart.objects.get_or_create(product=product)
            if is_created:
                cart_product.qty = qty
            else:
                cart_product.qty += qty
            cart_product.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next = self.request.GET.get("next")
        if next:
            return next
        return reverse("webapp:index")


class CartView(ListView):
    model = Cart
    template_name = "cart/cart_view.html"
    context_object_name = "cart"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['total'] = Cart.get_total()
        context['form'] = OrderForm()
        return context


class CartDeleteView(DeleteView):
    model = Cart
    success_url = reverse_lazy('webapp:cart')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)


class CartDeleteOneView(DeleteView):
    model = Cart
    success_url = reverse_lazy('webapp:cart')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        cart = self.object
        cart.qty -= 1
        if cart.qty < 1:
            cart.delete()
        else:
            cart.save()
        return HttpResponseRedirect(success_url)

webapp/views/order.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import OrderForm
from webapp.models import Order


class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'order/order_list.html'
    context_object_name = 'orders'

    def get_queryset(self):
        if self.request.user.has_perm('webapp.oder_view'):
            return Order.objects.all().order_by('-created_at')
        return self.request.user.orders.all().order_by('-created_at')


class OrderDetailView(DetailView):
    model = Order
    template_name = 'order/order_view.html'
    context_object_name = 'order'


class OrderCreateView(PermissionRequiredMixin, CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'order/order_create.html'
    permission_denied_message = "Доступ запрещён"

    def has_permission(self):
        return self.request.user.has_perm("webapp.order_add")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('webapp:order_view', kwargs={'pk': self.object.pk})


class OrderUpdateView(PermissionRequiredMixin, UpdateView):
    model = Order
    form_class = OrderForm
    template_name = 'order/order_update.html'
    permission_required = 'webapp.order_update'
    permission_denied_message = "Доступ запрещён"

    def get_success_url(self):
        return reverse('webapp:order_view', kwargs={'pk': self.object.pk})


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy('webapp:order_list')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

webapp/views/products.py
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, DeleteView, DetailView, CreateView
from webapp.views.base_view import SearchView

from webapp.forms import ProductForm
from webapp.models import Product


class IndexView(SearchView):
    model = Product
    template_name = 'product/index.html'
    ordering = ['category', 'p_name']
    search_fields = ['p_name__icontains']
    paginate_by = 6
    context_object_name = 'products'

    def get_queryset(self):
        return super().get_queryset().filter(balance__gt=0)


class ProductView(DetailView):
    model = Product
    template_name = 'product/product_view.html'
    queryset = Product.objects.filter(balance__gt=0)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_create.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return self.request.user.has_perm("webapp.product_create")


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_update.html'

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})

    def has_permission(self):
        return self.request.user.has_perm("webapp.product_update")


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    success_url = reverse_lazy('webapp:index')

    def has_permission(self):
        return self.request.user.has_perm("webapp.product_delete")

webapp/templates/order/order_create.html
{% extends 'base.html' %}

{% block title %}
    Создать заказ
{% endblock %}

{% block content %}
    <h1>Создать заказ</h1>
    <form action="" method="post">
        {% include 'partial/form.html' %}

        <input type="submit" value="Создать" class="btn btn-success">
        <button onclick="history.back()" class="btn btn-warning">Отмена</button>
    </form>
{% endblock %}

webapp/templates/order/order_list.html
{% extends 'base.html' %}

{% block title %}Заказы{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

    <h1 class="text-center">Заказы</h1>
    <table class="table table-striped">
                {% if orders == user %}
        <thead>
        <tr>
            <th scope="col">Номер заказа</th>
            <th scope="col">Заказчик</th>
            <th scope="col">Телефон</th>
            <th scope="col">Дата создания</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.pk }}</td>
                <td>{{ order.name }}</td>
                <td>{{ order.phone }}</td>
                <td>{{ order.created_at|date:'d.m.Y' }}</td>
                <td>
                    <a href="{% url 'webapp:order_view' order.pk %}">Просмотр</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
                    {% endif %}
    </table>
{% endblock %}

webapp/templates/order/order_product_add.html
{% extends 'base.html' %}

{% block title %}
    Добавить товар
{% endblock %}

{% block content %}
    <h1>Добавить товар к заказу</h1>
    <form action="" method="post">
        {% include 'partial/form.html' %}

        <input type="submit" value="Добавить" class="btn btn-success">
        <button onclick="history.back()" class="btn btn-warning">Отмена</button>
    </form>
{% endblock %}

webapp/templates/order/order_update.html
{% extends 'base.html' %}

{% block title %}
    Редактировать заказ {{ order.pk }}
{% endblock %}

{% block content %}
    <h1>Редактировать заказ "{{ order.pk }}"</h1>
    <form action="" method="post">
        {% include 'partial/form.html' %}
        <input type="submit" value="Редактировать" class="btn btn-success">
        <button onclick="history.back()" class="btn btn-warning">Отмена</button>
    </form>
{% endblock %}

webapp/templates/order/order_view.html
{% extends 'base.html' %}
{% block title %}Заказ {{ order.pk }}{% endblock %}
{% block content %}
    <div class="card text-center">
        <div class="card-header">
            <ul class="nav nav-pills card-header-pills">
                {% if perms.webapp.order_update %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:order_update' order.pk %}">Редактировать заказ</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <div class="card-body">
            <h5 class="card-title">Заказ "{{ order.pk }}"</h5>
            <p class="card-text"><small>Заказчик: </small>{{ order.name }}</p>
            <p class="card-text"><small>Контактные данные: </small>{{ order.phone }}</p>
            <p class="card-text"><small>Дата создания заказа: </small>{{ order.created_at|date:'d.m.Y' }}</p>

            <table class="table col-6">
                <thead>
                <tr>
                    <th scope="col">Товар</th>
                    <th scope="col">Количество</th>
                    {% if perms.webapp.can_update_product_in_order or perms.webapp.can_delete_product_from_order %}
                        <th scope="col" colspan="2">Действия</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        {% for product in order.products.all %}
                            <p>{{ product }}</p>
                        {% empty %}
                            <small>Пока нет товаров</small>
                        {% endfor %}
                    </td>
                    <td>
                        {% for product_in_order in order.order_products.all %}
                            <p>{{ product_in_order.amount }}</p>
                        {% endfor %}
                    </td>
                    <td>
                        {% for product in order.order_products.all %}
                            {% if perms.webapp.can_update_product_in_order %}
                                <a class="nav-link" href="{% url 'webapp:order_update' product.pk %}">Редактировать</a>
                            {% endif %}
                        {% endfor %}
                    </td>
                    <td>
                        {% for product in order.order_products.all %}
                            {% if perms.webapp.order_delete %}
                                <a class="nav-link"
                                   href="{% url 'webapp:order_delete' product.pk %}">Удалить</a>
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}